version: "3.5"

services:
  spark-python-compatibility-test:
    platform: linux/amd64
    image: rangareddy1988/python-compatibility-test:latest
    container_name: python-compatibility-test
    volumes:
      - ./data:/opt/data
      - $HOME/.m2:/root/.m2
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576