version: "3.5"

services:
  spark-python-compatibility-test:
    image: rangareddy1988/spark-python-compatibility-test:latest
    container_name: spark-python-compatibility-test
    volumes:
      - ./data:/opt/data
      - $HOME/.m2:/root/.m2